-- ? 1. Modelo de Datos (Oracle 19c)
CREATE TABLE OPERACIONES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUM1 NUMBER,
    NUM2 NUMBER,
    OPERACION VARCHAR2(20),
    RESULTADO NUMBER,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;